name: HubSpot Google Sheets Sync

on:
  schedule:
    # Runs at 9 AM and 5 PM UTC every day
    - cron: '0 9,17 * * *'
  workflow_dispatch:
    inputs:
      run_type:
        description: 'Type of sync to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - test

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_type == 'full')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run HubSpot Google Sheets Sync
      env:
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        echo "Checking service account key..."
        echo "Key length: ${#SERVICE_ACCOUNT_KEY}"
        echo "First 10 chars: ${SERVICE_ACCOUNT_KEY:0:10}..."
        echo "Last 10 chars: ...${SERVICE_ACCOUNT_KEY: -10}"
        
        # Test base64 decoding
        echo $SERVICE_ACCOUNT_KEY | base64 -d > /dev/null 2>&1
        if [ $? -eq 0 ]; then
          echo "Base64 validation successful"
        else
          echo "Warning: Service account key may not be properly base64 encoded"
        fi
        
        # Run the script
        python scripts/hs_gs.py

  manual-sync:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_type == 'test'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run Test Sync
      env:
        HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        echo "Checking service account key..."
        echo "Key length: ${#SERVICE_ACCOUNT_KEY}"
        echo "First 10 chars: ${SERVICE_ACCOUNT_KEY:0:10}..."
        echo "Last 10 chars: ...${SERVICE_ACCOUNT_KEY: -10}"
        
        # Test base64 decoding
        echo $SERVICE_ACCOUNT_KEY | base64 -d > /dev/null 2>&1
        if [ $? -eq 0 ]; then
          echo "Base64 validation successful"
        else
          echo "Warning: Service account key may not be properly base64 encoded"
        fi
        
        echo "Running test sync..."
        python scripts/hs_gs.py 